### ISSUE TITLE
Problem with ui-validate for password confirm

### ISSUE THREAD

**Issue by smcardle** [angular-ui/ui-utils#280]
Hi Guys

I have a problem using the ui-validate with a Confirm password field.
I have the following HTML snippet in my form

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" data-ng-model="credentials.password" placeholder="Password" >
                </div>
                <div class="form-group">
                    <label for="confirm_password">Confirm Password</label>
                    <input type="password" id="confirm_password" name="confirm_password" placeholder="Confirm Password" ui-validate=" '$value==credentials.password' "
                           ui-validate-watch=" 'credentials.password' " >
                    <div>
                        Passwords match? {{!!form.confirm_password.$error.validator}}
                    </div>
                </div>

The problem is I get this error in the console log when loading the page

Error: [$compile:ctreq] Controller 'ngModel', required by directive 'uiValidate', can't be found!
http://errors.angularjs.org/1.2.22/$compile/ctreq?p0=ngModel&p1=uiValidate
    at http://localhost:5555/lib/angular/angular.js:78:12
    at getControllers (http://localhost:5555/lib/angular/angular.js:6524:19)
    at nodeLinkFn (http://localhost:5555/lib/angular/angular.js:6693:35)
    at compositeLinkFn (http://localhost:5555/lib/angular/angular.js:6086:13)
    at compositeLinkFn (http://localhost:5555/lib/angular/angular.js:6089:13)
    at compositeLinkFn (http://localhost:5555/lib/angular/angular.js:6089:13)
    at nodeLinkFn (http://localhost:5555/lib/angular/angular.js:6686:24)
    at compositeLinkFn (http://localhost:5555/lib/angular/angular.js:6086:13)
    at compositeLinkFn (http://localhost:5555/lib/angular/angular.js:6089:13)
    at nodeLinkFn (http://localhost:5555/lib/angular/angular.js:6686:24) <input type="password" id="confirm_password" name="confirm_password" class="form-control" placeholder="Confirm Password" ui-validate=" '$value==credentials.password' " ui-validate-watch=" 'credentials.password' "> 

This would suggest that I also need to put an ng-model attribute on the Confirm Password input ???

I cannot put ng-model='credentials.password' as the Confirm Password input field would auto update as I type into the normal Password field !!!!

So what do I put here ????

I had assumed that the ui-validate-watch would handle the model watching...

My case is almost exactly the same as the example in the docs and examples I have found online but I cannot for the life of me see how these could possibly work considering the uiValidate directive has a required: 'ngModel'

Any help here would be great...

Regards

Steve

**Comment by PowerKiKi** [comment]
UI.Utils modules was split in individuals repositories. If still valid, please consider re-submitting on its dedicated repository: https://github.com/angular-ui/ui-validate

See the [README for details](https://github.com/angular-ui/ui-utils#readme).
