### ISSUE TITLE
UI scroll error through in DOM with ionic

### ISSUE THREAD

**Issue by cedriclombardot** [angular-ui/ui-utils#282]
Hi 

When i activate ui-scroll i saw this error. Have you got an idea on how to fix ?

Thanks in advance

````
TypeError: Cannot read property 'paddingTop' of null
    at getMeasurements (src/scripts/ui-scroll-jqlite.js:1168:53)
    at getWidthHeight (src/scripts/ui-scroll-jqlite.js:1185:26)
    at Object.angular.forEach.outerHeight (src/scripts/ui-scroll-jqlite.js:1238:20)
    at adjustRowHeight (src/scripts/ui-scroll-jqlite.js:1630:98)
    at src/scripts/ui-scroll-jqlite.js:1693:19
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:21984:28
    at completeOutstandingRequest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12194:10)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12495:7 ionic.bundle.js:17763
(anonymous function) ionic.bundle.js:17763
(anonymous function) ionic.bundle.js:15110
(anonymous function) ionic.bundle.js:21987
completeOutstandingRequest ionic.bundle.js:12194
(anonymous function)

````

**Comment by cranesandcaff** [comment]
I am also getting the same error.

**Comment by PowerKiKi** [comment]
@cranesandcaff if you are able to create a plunkr to demonstrate the issue, you'll have more change to get somebody involved to fix it.

**Comment by mfeingold** [comment]
Can you provide a repro. Based on the info you provided it is difficult to
say what's wrong

**Comment by mfeingold** [comment]
no repro forthcoming
